<?php
/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) 2018 HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */

namespace humhub\modules\themebuilder\controllers;

use humhub\modules\admin\components\Controller;
use humhub\modules\themebuilder\models\CreateTheme;
use humhub\modules\themebuilder\Module;
use Yii;

/**
 * Class
 *
 * @property Module $module
 */
class AdminController extends Controller
{

    /**
     * Select or create a theme
     */
    public function actionIndex()
    {
        $model = new CreateTheme();

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->save()) {
            return $this->redirect(['/theme-builder/theme', 'name' => $model->name]);
        }

        return $this->render('index', [
            'model' => $model,
            'module' => $this->module,
            'themes' => $this->module->getBaseThemes(),
            'editableThemes' => $this->module->getEditableThemes(),
        ]);
    }


    public function afterAction($action, $result)
    {
        Yii::$app->settings->delete('themeParents');

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

}