<?php
/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) 2021 HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */

namespace humhub\modules\themebuilder\commands;

use humhub\modules\themebuilder\helpers\ThemeHelper;
use Yii;

/**
 * This command is responsible for recompile LESS files of the themes.
 */
class CompileLess
{
    public static function runTheme($themeName, $pathToLessc = null)
    {
        self::log('Compiling LESS files of the theme "' . $themeName . '"...');

        $pathToLessc = self::getLesscCmd($pathToLessc);

        $theme = ThemeHelper::getThemeByName($themeName);
        if (!$theme) {
            self::error('Theme "' . $themeName . '" is not found by name!');
        }

        self::compileTheme($theme, $pathToLessc);

        self::log('Completed.');
    }

    public static function runAllThemes($pathToLessc = null)
    {
        self::log('Compiling LESS files of the themes:');

        $pathToLessc = self::getLesscCmd($pathToLessc);

        $themes = ThemeHelper::getThemes();
        /*
        foreach ($themes as $t => $theme) {
            if (!file_exists($theme->getBasePath() . DIRECTORY_SEPARATOR . 'tb_last_compile')) {
                // Skip themes without the file `tb_last_compile` in the theme root folder because
                // it indicates the theme is generated by the theme builder
                unset($themes[$t]);
            }
        }
        */
        unset($themes['enterprise']);
        unset($themes['HumHub']);

        if (empty($themes)) {
            self::error('No themes found!');
        }

        foreach ($themes as $theme) {
            self::log('- ' . $theme->name . '... ', '');
            self::compileTheme($theme, $pathToLessc);
            self::log('OK.');
        }

        self::log('Completed.');
    }

    protected static function getLesscCmd($pathToLessc = null)
    {
        if (empty($pathToLessc)) {
            $pathToLessc = 'lessc';
        }

        if (empty(shell_exec('which ' . escapeshellarg($pathToLessc)))) {
            self::error('Command "lessc" is not found' . ( $pathToLessc != 'lessc' ? ' in the path "' . $pathToLessc . '"' : '' ) . '!');
        }

        return $pathToLessc;
    }

    protected static function compileTheme($theme, $pathToLessc)
    {
        $lessFilePath = $theme->getBasePath() . DIRECTORY_SEPARATOR . 'less' . DIRECTORY_SEPARATOR . 'build.less';
        $cssFilePath = $theme->getBasePath() . DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR . 'theme.css';

        $preparedLessFilePath = self::prepareLessFile($lessFilePath);

        // Run compiling build.less into theme.css
        shell_exec($pathToLessc . ' -x ' . $preparedLessFilePath . ' ' . $cssFilePath);

        if ($preparedLessFilePath != $lessFilePath) {
            unlink($preparedLessFilePath);
        }
    }

    protected static function log($msg, $nl = "\n")
    {
        if (Yii::$app->request->isConsoleRequest) {
            print $msg . $nl;
        }
    }

    protected static function error($msg)
    {
        self::log($msg);
        self::log('Failed!');
        exit();
    }

    protected static function prepareLessFile($lessFilePath)
    {
        if (!file_exists($lessFilePath)) {
            self::error('Less file "' . $lessFilePath . '" is not found!');
        }

        $lessContent = file_get_contents($lessFilePath);
        if (preg_match_all('/@(HUMHUB|ENTERPRISE):[^;]+;/i', $lessContent, $lessVars)) {
            $lessPathInfo = pathinfo($lessFilePath);
            $preparedLessFilePath = $lessPathInfo['dirname'] . DIRECTORY_SEPARATOR . 'build-copy.less';
            $preparedLessFile = fopen($preparedLessFilePath, 'w');
            foreach ($lessVars[1] as $l => $lessVarName) {
                switch ($lessVarName) {
                    case 'HUMHUB':
                        $lessContent = str_replace($lessVars[0][$l], '@HUMHUB: "' . Yii::getAlias('@webroot-static/less') . '";', $lessContent);
                        break;
                    case 'ENTERPRISE':
                        if (Yii::$app->hasModule('enterprise-theme')) {
                            $lessContent = str_replace($lessVars[0][$l], '@ENTERPRISE: "' . Yii::$app->getModule('enterprise-theme')->getBasePath() . '";', $lessContent);
                        }
                        break;
                }
            }
            fwrite($preparedLessFile, $lessContent);
            fclose($preparedLessFile);
        } else {
            $preparedLessFilePath = $lessFilePath;
        }

        return $preparedLessFilePath;
    }
}
